variables:
  GIT_SUBMODULE_STRATEGY: recursive

build:
  image: docker:25
  stage: build
  script:
    - export IMAGE_NAME=$CI_REGISTRY/$CI_PROJECT_PATH
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $IMAGE_NAME:latest . -f Dockerfile
    - docker push $IMAGE_NAME -a
